[project]
name = "dnsquery"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dnspython>=2.7.0",
    "icecream>=2.1.4",
    "pyinstaller>=6.13.0",
]
