[project]
name = "market"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "icecream>=2.1.4",
    "matplotlib>=3.10.3",
    "prettytable>=3.16.0",
    "pyinstaller>=6.13.0",
    "requests>=2.32.3",
]
